spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: zlh1260788704
    url: jdbc:mysql://localhost:3306/freetogo?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      #password: 123456
#      database: 0 #操作的是0号数据库
#      jedis:
#        #Redis连接池配置
#        pool:
#          max-active: 8 #最大连接数
#          max-wait: 1ms #连接池最大阻塞等待时间
#          max-idle: 4 #连接池中的最大空闲连接
#          min-idle: 0 #连接池中的最小空闲连接
logging:
  level:
    com.softegg.freetogo.Api.alipay: debug